<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Perhitungan BTN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0521bc91-f998-4f30-8789-268f9b0527cc</testSuiteGuid>
   <testCaseLink>
      <guid>450097f8-4a52-4d41-92e4-d07871d8caa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test Hitung</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1cb926a1-782c-44ea-afb7-2399880f63c8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Testing BTN</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1cb926a1-782c-44ea-afb7-2399880f63c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>A</value>
         <variableId>96e016fd-cf80-400b-9a4e-07c700ab088a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1cb926a1-782c-44ea-afb7-2399880f63c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>B</value>
         <variableId>1464245a-f132-4340-aba9-2d5f1dbec607</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1cb926a1-782c-44ea-afb7-2399880f63c8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Expected</value>
         <variableId>ae1145bb-10df-49a6-8e0c-39193f062005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcad02e1-06c1-4138-a9a1-da5af23827b1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
