<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Per Bulan_floating-label-field</name>
   <tag></tag>
   <elementGuidId>399c79e1-cff2-4be0-9ff5-33835cf8b498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b22c8c7c-b1aa-49bd-9f96-4eb75a2d348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4166eb05-58de-40c8-9db1-61aab0f1a4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-label-field</value>
      <webElementGuid>18ede3b0-8d56-40e8-ac7f-15dc01035735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pengeluaran</value>
      <webElementGuid>a0298795-8f16-46ca-b7a9-0f45fc5ffcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c1daec1c-6c33-4f7c-8d9d-1f121906d351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_hitung_harga&quot;)/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;floating-label-wrap&quot;]/input[@class=&quot;floating-label-field&quot;]</value>
      <webElementGuid>c4f84e08-a770-4cc4-8ca9-260eb7e5a7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[4]</value>
      <webElementGuid>01f51e8a-02ba-4270-ab61-fe10c09c804c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_hitung_harga']/div/div[2]/input</value>
      <webElementGuid>80c6d2f9-c15e-465a-ac4e-e39bfe82f7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>f80ae50b-94b9-4181-8986-a14d363e1887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Pengeluaran']</value>
      <webElementGuid>562528a6-acc8-4064-984b-5894dc870ded</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
